In [ ]:
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
scalar.ndim

0

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant(
          [
         [1,2,3],
         [4,5,6]
]
)
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
matrix.shape

TensorShape([2, 3])

In [ ]:
tensor = tf.constant(

         [[[1,2,3],
         [4,5,6]]]
)
tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([1, 2, 3])

In [ ]:
changable_tensor = tf.Variable(7)
changable_tensor

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>

In [ ]:
changable_tensor.shape

TensorShape([])

In [ ]:
changable_vector = tf.Variable([10,7])
changable_vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
changable_vector[0].assign(9)
changable_vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:
rand1 = tf.random.normal(shape=(3,3))
rand2 = tf.random.normal(shape=(3,3))
rand1,rand2,rand1 == rand2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.09355379, -1.4502958 ,  0.55636376],
        [-0.82070816,  1.7830908 , -0.19645676],
        [ 0.356942  , -0.31136838,  0.4344439 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.4287429 ,  0.03309121, -0.13065538],
        [ 0.19798514,  0.51671284, -0.16745326],
        [-2.1648443 ,  1.0152651 , -0.6449752 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False],
        [False, False, False]])>)

In [ ]:
rand3 = rand1 - rand2
rand3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3351891, -1.483387 ,  0.6870191],
       [-1.0186933,  1.2663779, -0.0290035],
       [ 2.5217862, -1.3266335,  1.0794191]], dtype=float32)>

In [ ]:
rand3 = rand1 + rand2
rand3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.52229667, -1.4172046 ,  0.42570838],
       [-0.622723  ,  2.2998037 , -0.36391002],
       [-1.8079023 ,  0.70389676, -0.2105313 ]], dtype=float32)>

In [ ]:
rand3 = rand1 * rand2
rand3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.04011052, -0.04799205, -0.07269192],
       [-0.16248803,  0.92134595,  0.03289732],
       [-0.77272385, -0.31612146, -0.28020552]], dtype=float32)>

In [ ]:
rand3 = rand1 / rand2
rand3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[  0.21820487, -43.827217  ,  -4.2582536 ],
       [ -4.145302  ,   3.4508352 ,   1.1732036 ],
       [ -0.16488114,  -0.30668676,  -0.6735823 ]], dtype=float32)>

In [ ]:
rand3 = tf.random.uniform(minval=0,maxval=8,shape=(3,3),dtype=tf.int32)
rand3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 7, 6],
       [7, 5, 0],
       [4, 4, 7]], dtype=int32)>

In [ ]:
Float_tensor = tf.constant(7,dtype=tf.float16)
Float_tensor

<tf.Tensor: shape=(), dtype=float16, numpy=7.0>

In [ ]:

tf.random.Generator.from_seed(7)


not_shuffled = tf.random.normal(shape=(3,3))
print(f"not shuffled: {not_shuffled}")

shuffled = tf.random.shuffle(not_shuffled)
print(f"shuffled: {shuffled}")

not shuffled: [[ 1.0647489  -0.6003843  -0.36290523]
 [ 0.36409935 -1.4332219  -1.2510613 ]
 [ 0.3397326  -0.840685   -0.97895944]]
shuffled: [[ 0.3397326  -0.840685   -0.97895944]
 [ 1.0647489  -0.6003843  -0.36290523]
 [ 0.36409935 -1.4332219  -1.2510613 ]]


In [ ]:
tf.ones((2,3,10))

<tf.Tensor: shape=(2, 3, 10), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
numpy_A = np.arange(1,10)
numpy_A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
A = tf.constant(numpy_A,shape=(3,3))
A

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [ ]:
A.dtype

tf.int64

In [ ]:
A.shape

TensorShape([3, 3])

In [ ]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
tf.matmul(A,A),tf.multiply(A,A)

(<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
 array([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])>,
 <tf.Tensor: shape=(3, 3), dtype=int64, numpy=
 array([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])>)

In [ ]:
B = tf.matmul(A,A)

In [ ]:
tf.reduce_min(B),tf.reduce_max(B),tf.reduce_sum(B),tf.reduce_mean(B)

(<tf.Tensor: shape=(), dtype=int64, numpy=30>,
 <tf.Tensor: shape=(), dtype=int64, numpy=150>,
 <tf.Tensor: shape=(), dtype=int64, numpy=729>,
 <tf.Tensor: shape=(), dtype=int64, numpy=81>)

In [ ]:
tfp.stats.variance(B)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 864, 1350, 1944])>

In [ ]:
tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 30,  66, 102],
       [ 36,  81, 126],
       [ 42,  96, 150]])>

In [ ]:
C = tf.tensordot(B,B,1).numpy()
C

array([[ 7560,  9288, 11016],
       [17118, 21033, 24948],
       [26676, 32778, 38880]])

In [ ]:
C = tf.cast(C,tf.float32)
C,tf.size(C).numpy()

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 7560.,  9288., 11016.],
        [17118., 21033., 24948.],
        [26676., 32778., 38880.]], dtype=float32)>,
 9)

In [ ]:
tf.math.reduce_variance(C)

<tf.Tensor: shape=(), dtype=float32, numpy=104307270.0>

In [ ]:
tf.reshape(C,(9,1))

<tf.Tensor: shape=(9, 1), dtype=float32, numpy=
array([[ 7560.],
       [ 9288.],
       [11016.],
       [17118.],
       [21033.],
       [24948.],
       [26676.],
       [32778.],
       [38880.]], dtype=float32)>

In [ ]:
tf.argmax(C).numpy()

array([2, 2, 2])

In [ ]:
tf.argmin(C).numpy()

array([0, 0, 0])

In [ ]:
C.shape

TensorShape([3, 3])

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape,G_squeezed

(TensorShape([50]),
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>)

In [ ]:
some_list = [0,1,2,3]

tf.one_hot(some_list,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,4,on_value=5,off_value=10)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 5, 10, 10, 10],
       [10,  5, 10, 10],
       [10, 10,  5, 10],
       [10, 10, 10,  5]], dtype=int32)>

In [ ]:
H = tf.range(1,10,dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float32)>

In [ ]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
I = H.numpy()
type(I)

numpy.ndarray